name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  # This action is modified from https://jacobian.org/til/github-actions-poetry/
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Cache the installation of Poetry
      - name: cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key:  poetry-1.3.1-0

      # Install poetry
      - uses: snok/install-poetry@v1
        with:
          version: 1.3.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      # Cache project dependencies
      - name: cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      # Install dependencies
      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'

      # Install package
      - run: poetry install --no-interaction

      # Build documentation
      - name: Sphinx Build
        run: |
          make -C docs html

      # Deploy docs to GitHub pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
        with:
          publish_branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true 
